# Local validator configuration
# Minimal setup for local development

global:
  environment: local
  namespace: kt-datahaven-local

image:
  tag: local
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: datahaven-dockerhub

# Ingress disabled for local (can be enabled for testing)
ingress:
  enabled: false
  perReplica: true
  wildcardDomain: local.datahaven.xyz
  # If enabled, this would generate:
  # - dh-validator-0.local.datahaven.xyz
  # - dh-validator-1.local.datahaven.xyz

node:
  chain: local
  chainData:
    storageClass: "hostpath"
    persistence:
      size: 10Gi
  chainKeystore:
    storageClass: "hostpath"
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
    customNodeKey:
      # To generate new key run: docker run --rm -t moonsonglabs/datahaven:latest key generate-node-key
      # 12D3KooWL5Av1ZZSKkaittmxXBmZpzP7zgiB1AAnWHEw7MxzqnFp
      - bdf71a910354e231095366230621eaefb5f99465045f1501478fd3d9b5deef98
      # 12D3KooWAxFonTS177T81CTDeH6mfvJQWYEJeVQ1gPrnULjNY8Cn
      - 2a775a9db9fb0ff40afacb4aa7ccbf2a5d04c6d980bb1437c196c8e38a6cd948

# Local development settings
development:
  debug: true
  fastRuntime: true