{{- if and .Values.ingress.enabled .Values.ingress.perReplica -}}
{{- $fullName := include "node.fullname" . -}}
{{- $replicas := .Values.node.replicas | int -}}
{{- range $i := until $replicas }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $i }}
  labels:
  {{- include "node.labels" $ | nindent 4 }}
    replica: "{{ $i }}"
  {{- with $.Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.ingress.ingressClassName }}
  ingressClassName: {{ $.Values.ingress.ingressClassName | quote }}
  {{- end }}
  rules:
    - host: {{ printf "%s-%d.%s" $fullName $i $.Values.ingress.wildcardDomain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}-{{ $i }}
                port:
                  number: {{ $.Values.node.perNodeServices.apiService.rpcPort }}
  {{- with $.Values.ingress.tls }}
  tls:
  {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}