# Lint and Format: CI for Rust components (DataHaven runtime and node Rust tests)
#
# Overview:
# 1. Check Rust Format: Check that the Rust code is formatted correctly
# 2. Check Rust Lint: Check that the Rust code is linted correctly

name: Lint and Format

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      pull_request:
        description: set to pull_request number to execute on external pr
        required: false

env:
  CARGO_TERM_COLOR: always
  WORKING_DIR: operator

jobs:
  cargo-fmt:
    name: "Check format with rustfmt"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/setup-rust
        with:
          cache-key: "LINT"

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

  check-rust-lint:
    name: "Check lint with clippy"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/actions/setup-rust
        with:
          cache-key: "LINT"

      - name: Run cargo clippy
        run: SKIP_WASM_BUILD=1 env -u RUSTFLAGS cargo clippy --features try-runtime,runtime-benchmarks --locked
        env:
          RUSTFLAGS: -D warnings
